// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjhVz6Q-ExXISNTDRjojEFYF5ALMCgmqQ',
    appId: '1:526285433869:web:a34b3f0d55c55314513944',
    messagingSenderId: '526285433869',
    projectId: 'minecraft-server-automation',
    authDomain: 'minecraft-server-automation.firebaseapp.com',
    storageBucket: 'minecraft-server-automation.firebasestorage.app',
    measurementId: 'G-JVQ493KZWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOiE5InESALt-DA9n-KeodPBAttWND1U',
    appId: '1:526285433869:android:69b9a5621335c3ce513944',
    messagingSenderId: '526285433869',
    projectId: 'minecraft-server-automation',
    storageBucket: 'minecraft-server-automation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Ifpv3rBW4sM2ATtsRrjmECEtnCZBuCQ',
    appId: '1:526285433869:ios:e9118f2900663962513944',
    messagingSenderId: '526285433869',
    projectId: 'minecraft-server-automation',
    storageBucket: 'minecraft-server-automation.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Ifpv3rBW4sM2ATtsRrjmECEtnCZBuCQ',
    appId: '1:526285433869:ios:e9118f2900663962513944',
    messagingSenderId: '526285433869',
    projectId: 'minecraft-server-automation',
    storageBucket: 'minecraft-server-automation.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjhVz6Q-ExXISNTDRjojEFYF5ALMCgmqQ',
    appId: '1:526285433869:web:46ccdb68f69189e2513944',
    messagingSenderId: '526285433869',
    projectId: 'minecraft-server-automation',
    authDomain: 'minecraft-server-automation.firebaseapp.com',
    storageBucket: 'minecraft-server-automation.firebasestorage.app',
    measurementId: 'G-KWKCR62QXS',
  );
}
