name: Cleanup PR Resources

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      pull-requests: write
    
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Cleanup PR resources
      run: |
        echo "Cleanup completed for PR #${{ github.event.pull_request.number }}"
        echo "iOS build artifacts will be automatically cleaned up after retention period"
        
    - name: Comment PR with cleanup status
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `## 🧹 Cleanup completed
            
            The iOS build artifacts for this PR will be automatically cleaned up after the retention period.
            
            - Build Artifact: \`ios-build-pr-${{ github.event.pull_request.number }}\`
            - Retention: 7 days
            
            ---
            *This PR has been closed and resources will be cleaned up automatically.*`
          });
