name: Debug Firebase CLI Cache

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Manual trigger also available

jobs:
  debug-firebase-cache:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Cache Firebase CLI
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          /usr/local/lib/node_modules/firebase-tools
          /usr/local/bin/firebase
        key: ${{ runner.os }}-firebase-cli-v13-debug
        restore-keys: |
          ${{ runner.os }}-firebase-cli-v13-debug
          ${{ runner.os }}-firebase-cli-
        
    - name: Debug Firebase CLI Detection
      run: |
        echo "=== DEBUGGING FIREBASE CLI CACHE ==="
        echo "Current working directory: $(pwd)"
        echo "Current user: $(whoami)"
        echo "Home directory: $HOME"
        
        echo ""
        echo "=== NPM CONFIG ==="
        echo "npm prefix: $(npm config get prefix)"
        echo "npm global dir: $(npm config get prefix)/lib/node_modules"
        echo "npm bin dir: $(npm config get prefix)/bin"
        
        echo ""
        echo "=== PATH ANALYSIS ==="
        echo "Current PATH: $PATH"
        export PATH="$PATH:$(npm config get prefix)/bin"
        echo "Updated PATH: $PATH"
        
        echo ""
        echo "=== FILE SYSTEM CHECKS ==="
        echo "Checking /usr/local/bin/firebase:"
        ls -la /usr/local/bin/firebase 2>/dev/null || echo "  NOT FOUND"
        
        echo "Checking $(npm config get prefix)/bin/firebase:"
        ls -la $(npm config get prefix)/bin/firebase 2>/dev/null || echo "  NOT FOUND"
        
        echo "Checking /usr/local/lib/node_modules/firebase-tools:"
        ls -la /usr/local/lib/node_modules/firebase-tools 2>/dev/null || echo "  NOT FOUND"
        
        echo "Checking $(npm config get prefix)/lib/node_modules/firebase-tools:"
        ls -la $(npm config get prefix)/lib/node_modules/firebase-tools 2>/dev/null || echo "  NOT FOUND"
        
        echo ""
        echo "=== COMMAND CHECKS ==="
        echo "command -v firebase result:"
        command -v firebase 2>&1 || echo "  NOT FOUND"
        
        echo "which firebase result:"
        which firebase 2>&1 || echo "  NOT FOUND"
        
        echo ""
        echo "=== CACHE DIRECTORIES ==="
        echo "~/.npm contents:"
        ls -la ~/.npm/ 2>/dev/null || echo "  EMPTY"
        
        echo ""
        echo "=== DECISION LOGIC ==="
        if [ -f "/usr/local/bin/firebase" ] || [ -f "$(npm config get prefix)/bin/firebase" ]; then
          echo "DECISION: Firebase CLI found in filesystem - SKIP INSTALL"
        elif command -v firebase &> /dev/null; then
          echo "DECISION: Firebase CLI found in PATH - SKIP INSTALL"
        else
          echo "DECISION: Firebase CLI not found - INSTALL NEEDED"
        fi
        
    - name: Install Firebase CLI (if needed)
      run: |
        export PATH="$PATH:$(npm config get prefix)/bin"
        
        if [ -f "/usr/local/bin/firebase" ] || [ -f "$(npm config get prefix)/bin/firebase" ]; then
          echo "Firebase CLI found in filesystem, checking version..."
          firebase --version
        elif command -v firebase &> /dev/null; then
          echo "Firebase CLI found in PATH, checking version..."
          firebase --version
        else
          echo "Installing Firebase CLI..."
          npm install -g firebase-tools@13 --no-audit --no-fund
          echo "Installation complete, checking version..."
          firebase --version
        fi
        
    - name: Post-install verification
      run: |
        echo "=== POST-INSTALL VERIFICATION ==="
        echo "Firebase version:"
        firebase --version
        
        echo ""
        echo "Firebase location:"
        which firebase
        
        echo ""
        echo "Files after install:"
        ls -la /usr/local/bin/firebase 2>/dev/null || echo "  /usr/local/bin/firebase not found"
        ls -la $(npm config get prefix)/bin/firebase 2>/dev/null || echo "  npm bin firebase not found"
