name: Deploy to Firebase Hosting (Master)

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        cache: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Cache Firebase CLI
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          /opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/firebase-tools
          /opt/hostedtoolcache/node/18.20.8/x64/bin/firebase
        key: ${{ runner.os }}-firebase-cli-v13
        restore-keys: |
          ${{ runner.os }}-firebase-cli-
        
    - name: Install Firebase CLI
      run: |
        # Check if firebase-tools is already installed globally
        export PATH="$PATH:$(npm config get prefix)/bin"
        if ! command -v firebase &> /dev/null; then
          echo "Installing Firebase CLI..."
          npm install -g firebase-tools@13 --no-audit --no-fund
        else
          echo "Firebase CLI already installed, checking version..."
          firebase --version
        fi
      
    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          app/.dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('app/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
        
    - name: Install Flutter dependencies
      run: |
        cd app
        flutter pub get
        
    - name: Run Flutter tests
      run: |
        cd app
        flutter test --coverage
        
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
        
    - name: Generate HTML coverage report
      run: |
        cd app
        # Generate HTML coverage report with correct prefix to avoid path duplication
        # Use absolute path to ensure correct prefix removal
        genhtml coverage/lcov.info -o coverage/html --prefix "$(pwd)/lib"
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: app/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        
    - name: Verify iOS build configuration
      run: |
        cd app
        echo "Verifying iOS build configuration..."
        flutter doctor
        echo "iOS build would require macOS runner - skipping actual build"
        echo "Bundle ID: com.screendead.servers"
        echo "Platform: iOS only"
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: app/coverage/
